### PR TITLE
self-hosted plausible analytics instead of google analytics

### PR DESCRIPTION
**Pull request by JeffaloBob**
i think w_l said yes but its hard to tell, 
analytics can be seen at [https://analytics.jeffalo.net/share/0KJg9I2FYX3bYHx50hhd_](https://analytics.jeffalo.net/share/0KJg9I2FYX3bYHx50hhd_) 

dm me for password

### CODE REVIEW

**Comment by JeffaloBob** [comment]
apparently w_l said no :((

**Comment by GrahamSH-LLK** [comment]
@WorldLanguages changed his mind.

**Review by GrahamSH-LLK — APPROVED** [review]
This PR is utterly amazing and should be implemented immediatly.

**Comment by Hans5958** [comment]
Any reasons why? It seems that I trusted Google Analytics that won't ever gloss our data due to the volume, than using your instance that might be taken down sometime in the future. There could be many reasons, but it's a possibility nevertheless.

Also, it's not "perfect," it's just a provider change of a well-established analytics into another, self-hosted, well-established analytics. That's it.

**Pull request closed without merging**
