### PR TITLE
Add sitemap

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This adds an automatic sitemap.xml to the built site. This is helpful for SEO.

### CODE REVIEW

**Comment by Hans5958** [comment]
Just confirming, do you the steps listed [here](https://github.com/jekyll/jekyll-sitemap) (including running bundle), instead of doing this manually. I am away from my computer so I couldn't check it for the time being.

**Comment by GrahamSH-LLK** [comment]
> Just confirming, do you the steps listed [here](https://github.com/jekyll/jekyll-sitemap) (including running bundle), instead of doing this manually? I am away from my computer so I couldn't check it for the time being.

I ran bundle locally, and copied the changes. Everything should work.

**Comment by GrahamSH-LLK** [comment]
@Hans5958 Is this good to merge?

**Comment by Hans5958** [comment]
Sorry for waiting. It was midnight on the time of my last comment. I will check this now.

**Review by Hans5958 — APPROVED** [review]
LGTM

**Pull request merged**
