### PR TITLE
New footer design

### PR DESCRIPTION
**Pull request by Hans5958**
Just a new footer design because there will be a need for more room for links later, and also so people can support us by starring our repo.

## Sample

image

image

image

image

### CODE REVIEW

**Review by WorldLanguages — APPROVED** [review]
Looks good, but too similar to Scratch's footer if you ask me :p

**Comment by Hans5958** [comment]
I mean, I can see why you would think that way, due to the wide margins, but that's because we only have few things to put there, and I created this inspired by other footers I found on the web.

**Comment by GrahamSH-LLK** [comment]
Do the buttons actually work?

**Comment by Hans5958** [comment]
> *always* blocked

Are you sure about that? I tested it, and unless you also blocked social buttons (usually I don't), the button will appear like the pictures above. Even so, it is logical and should not be a huge deal.

**Pull request merged**
