### PR TITLE
Add Changelog

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This adds a changelog to the site. It uses the changelogs written by @WorldLanguages. It's a .md. @Hans5958 @WorldLanguages

### CODE REVIEW

**Comment by Hans5958** [comment]
We haven't reach any consensus yet about where we should put it. I'm going to put this page as a redirect for now.

**Comment by GrahamSH-LLK** [comment]
Don't! If a page is a redirect, you don't want to change it. If you set it as a redirect, there's no turning back. (In my opinion)

**Comment by Hans5958** [comment]
> 
> 
> Don't! If a page is a redirect, you don't want to change it. If you set it as a redirect, there's no turning back. (In my opinion)

What do you mean no turning back? I can still edit the page on the redirect page, including replacing it with a normal page.

**Comment by WorldLanguages** [comment]
I'll be merging this for now, better than nothing

**Pull request merged**
