### PR TITLE
Better SEO

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This is still a WIP, so don't merge.

### CODE REVIEW

**Comment by Hans5958** [comment]
Reminder: FAQ is still on the WIP page.

**Comment by GrahamSH-LLK** [comment]
I know. I've merged that branch into mine.

**Review by wgyt735yt — APPROVED** [review]
Seems great! Glad we improved the SEO.

**Review by Hans5958 — APPROVED** [review]
lgtm

**Pull request merged**
